language: python

python: 
    - "2.6"
    - "2.7"

before_install: 
    # Environment setup
    - export VIRT_ROOT=/home/travis/virtualenv/python$TRAVIS_PYTHON_VERSION
    - export PKG_CONFIG_PATH=$VIRT_ROOT/lib/pkgconfig
    - pip install pip --upgrade
    - sudo apt-get -qq update
    - sudo apt-get install gettext python-gtk2 python-lxml git python-virtualenv libxslt1-dev pkg-config libjpeg-dev build-essential python-all-dev python-nose
    # build before install
    - mkdir -p /home/travis/virtualenv/
    - virtualenv $VIRT_ROOT --system-site-packages
    - mkdir -p $VIRT_ROOT/share
    - . $VIRT_ROOT/bin/activate
    - python setup.py -q build

install:
    - pip install coveralls
    - python setup.py -q install

script:
    - coverage run --source=bauble setup.py test

after_success:
    - coveralls
